#!/bin/sh
# Example root task for Debian/Ubuntu: update the system.
# Install into remote-runner-execd's -scripts-dir as root:
#   cp -r root-scripts-example/apt-update /var/lib/remote-runner/scripts/
apt update
apt upgrade -y
apt autoremove -y